config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  devise_for :users

  get "home/about" => "homes#about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource  :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers'  => 'relationships#followers',  as: 'followers'
    get "search", to: "users#search"
  end
  get "search" => "searches#search"
  resources :rooms,    only: [:create, :index, :show]
  resources :messages, only: [:create]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  get "search_book" => "books#search_book"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books,        dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,    dependent: :destroy
  has_many :entries,      dependent: :destroy
  has_many :messages,     dependent: :destroy
  has_many :view_counts,  dependent: :destroy
  has_many :group_users,  dependent: :destroy
  has_many :groups, through: :group_users
  has_many :relationships,            class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships,            source: :followed
  has_many :followers,  through: :reverse_of_relationships, source: :follower

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length:{maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content,method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE?',content + '%')
    elsif method == 'backward'
      User.where('name LIKE?','%' + content)
    else
      User.where('name LIKE?','%' + content + '%')
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit,:update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])

    # DM
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end

    @books = @user.books
    @book = Book.new

    # 投稿数（今日、前日、今週、前週）
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image,size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す",user_relationships_path(user.id),method: :delete %>
            <% else %>
              <%= link_to "フォローする",user_relationships_path(user.id),method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follows</th>
    <th><%= link_to user.followings.count,user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>Followers</th>
    <th><%= link_to user.followers.count,user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if user.name != "guestuser" %>
    <% if current_user != user %>
      <td><%= render "relationships/btn", user: user %></td>
    <% else %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class='row'>
  <% if user.id != current_user.id %>
    <% if (current_user.following? user) && (user.following? current_user) %>
    <% if @isRoom == true %>
      <%= link_to "DM", room_path(roomId), class: "btn btn-info btn-block" %>
    <% else %>
      <%= form_with model: @room do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: user.id %>
        <% end %>
        <%= f.submit "チャットを始める", class: "btn btn-primary btn-block" %>
      <% end %>
    <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto'>
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors',obj: @book %>
      <%= render 'books/form',book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <div><%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %></div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info',user: @user %>
      <h2 class='mt-3'>New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <div class="table_width">
        <!-- 今日と前日の投稿数 -->
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_book.count %></td>
              <td><%= @yesterday_book.count %></td>
              <td>
                <% if @yesterday_book.count == 0 %>
                  <p>前日の投稿はありません</p>
                <% else %>
                  <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
                  <%= (@the_day_before * 100).round %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>

        <!-- 今週と前週の投稿数 -->
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>今週の投稿数</th>
              <th>前週の投稿数</th>
              <th>前週比</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_book.count %></td>
              <td><%= @last_week_book.count %></td>
              <td>
                <% if @last_week_book.count == 0 %>
                  <p>前週の投稿はありません</p>
                <% else %>
                  <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
                  <%= (@the_week_before * 100).round %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>

        <!-- ７日分の投稿数 -->
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>６日前</th>
              <th>５日前</th>
              <th>４日前</th>
              <th>３日前</th>
              <th>２日前</th>
              <th>昨日</th>
              <th>今日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_6days.count %></td>
              <td><%= @books.created_5days.count %></td>
              <td><%= @books.created_4days.count %></td>
              <td><%= @books.created_3days.count %></td>
              <td><%= @books.created_2days.count %></td>
              <td><%= @yesterday_book.count %></td>
              <td><%= @today_book.count %></td>
            </tr>
          </tbody>
        </table>

        <!-- グラフ -->
        <canvas id="myLineChart"></canvas>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
          <script>
            $(document).on('turbolinks:load', function() {
              var ctx = document.getElementById("myLineChart");
              var myLineChart = new Chart(ctx, {
                type: 'line',
                data: {
                  labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
                  datasets: [
                    {
                      label: '投稿した本の数',
                      data: [<%= @books.created_6days.count %>, <%= @books.created_5days.count %>, <%= @books.created_4days.count %>, <%= @books.created_3days.count %>, <%= @books.created_2days.count %>, <%= @yesterday_book.count %>, <%= @today_book.count %>],
                      borderColor: "rgba(0,0,255,1)",
                      backgroundColor: "rgba(0,0,0,0)"
                    }
                  ],
                },
                options: {
                  title: {
                    display: true,
                    text: '７日間の投稿数の比較'
                  },
                  scales: {
                    yAxes: [{
                      ticks: {
                        suggestedMax: 10,
                        suggestedMin: 0,
                        stepSize: 1,
                        callback: function(value, index, values){
                          return value
                        }
                      }
                    }]
                  },
                }
              });
            });
          </script>

        <!-- 指定した日の記録（投稿数） -->
        <%= form_with url: user_search_path(@user), local: false, method: :get do |f| %>
          <%= f.date_field :created_at %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>

        <div id="search_result">
          <% if @search_book.present? %>
            <%= render 'search', search_book: @search_book %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>