config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  devise_for :users

  get "home/about" => "homes#about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource  :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers'  => 'relationships#followers',  as: 'followers'
    get "search", to: "users#search"
  end
  get "search" => "searches#search"
  resources :rooms,    only: [:create, :index, :show]
  resources :messages, only: [:create]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  get "search_book" => "books#search_book"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  has_many :book_comments,   dependent: :destroy
  has_many :favorites,       dependent: :destroy
  has_many :view_counts,     dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  validates :title, presence:true
  validates :body,  presence:true, length:{maximum:200}

  # 新着順、評価の高い順
  scope :latest,     -> { order(created_at: :desc) }
  scope :star_count, -> { order(star: :desc) }
  # 投稿数（今日、前日、７日分、今週、前週）
  scope :created_today,     -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2days,     -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3days,     -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4days,     -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5days,     -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6days,     -> { where(created_at: 6.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content,method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE?',content + '%')
    elsif method == 'backward'
      Book.where('title LIKE?','%' + content)
    else
      Book.where('title LIKE?','%' + content + '%')
    end
  end

  def self.search(search_word)
    Book.where(['category LIKE ?', "#{search_word}"])
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users
  has_many :users, through: :group_users

  validates :name,         presence: true
  validates :introduction, presence: true

  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image: 'no_image.jpg'
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :content, presence: true, length:{maximum: 200}

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower,class_name: "User"
  belongs_to :followed,class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries,  dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books,        dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,    dependent: :destroy
  has_many :entries,      dependent: :destroy
  has_many :messages,     dependent: :destroy
  has_many :view_counts,  dependent: :destroy
  has_many :group_users,  dependent: :destroy
  has_many :groups, through: :group_users
  has_many :relationships,            class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships,            source: :followed
  has_many :followers,  through: :reverse_of_relationships, source: :follower

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length:{maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content,method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE?',content + '%')
    elsif method == 'backward'
      User.where('name LIKE?','%' + content)
    else
      User.where('name LIKE?','%' + content + '%')
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :current_user,only:[:edit,:update,:destroy]

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @book_comment = BookComment.new

    # 閲覧数
    @book_detail = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book_detail.id)
      current_user.view_counts.create(book_id: @book_detail.id)
    end
  end

  def index
    to  = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    @book = Book.new

    # 新しい順、評価の高い順
    if params[:latest]
      @books = Book.latest
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search_book
    @book = Book.new
    @books = Book.search(params[:keyword])
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :comment, :star, :category)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :tag %>
    <%= f.text_field :category, class: 'form-control book_category' %>
  </div>
  <div class="field" id="star">
    <%= f.label :star, "Rate" %>
    <%= f.hidden_field :star, id: :review_star %>
  </div>
  <script>
    $('#star').raty({
      size: 36,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn: '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[star]',
      half: true,
    });
  </script>
  <div class="form-group">
    <%= f.submit 'Create Book',class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
              <%= image_tag book.user.get_profile_image, size:'50x50' %>
            <% end %>
        </td>
        <td><%= link_to book.title,book,class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/btn",book: book %>
        </td>
        <td>コメント数: <%= book.book_comments.count %></td>
        <td>閲覧数: <%= book.view_counts.count %></td>
        <td>
          <span id="star-rate-<%= book.id %>"></span>
          <script>
            $('#star-rate-<%= book.id %>').raty({
              size: 36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn: '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= book.star %>,
            });
          </script>
          <%= book.star %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <%= render 'layouts/errors', obj: @book %>
        <div class="form-group">
          <label for="inputTitle">Title</label>
          <%= f.text_field :title,autofocus: true,id:"inputTitle",placeholder:"タイトル",class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="inputOpinion">Opinion</label>
          <%= f.text_area :body,autofocus: true,class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.label :tag %>
          <%= f.text_field :category, class: 'form-control book_category' %>
        </div>
        <div>
          <span id="star-rate-<%= @book.id %>"></span>
          <script>
            $('#star-rate-<%= @book.id %>').raty({
              size: 36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn: '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @book.star %>,
            });
          </script>
          <%= @book.star %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book",class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to 'Show', @book %> |
      <%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors',obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>

      <div class="row">
        <%= link_to "新しい順", books_path(latest: "true") %> |
        <%= link_to "評価の高い順", books_path(star_count: "true") %>
      </div>

      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/search_book.html.erb
<div class="container">
  <div class="row">
    <h3>Books search for "<%= params[:keyword] %>"</h3>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th>Tag</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image, size:'50x50' %>
              <% end %>
            </td>
            <td><%= link_to book.title,book,class: "book_#{book.id}" %></td>
            <td><%= book.body %></td>
            <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
            <td id="favorite_buttons_<%= book.id %>">
              <%= render "favorites/btn",book: book %>
            </td>
            <td>コメント数: <%= book.book_comments.count %></td>
            <td>閲覧数: <%= book.view_counts.count %></td>
            <td>
              <span id="star-rate-<%= book.id %>"></span>
              <script>
                $('#star-rate-<%= book.id %>').raty({
                  size: 36,
                  starOff: '<%= asset_path('star-off.png') %>',
                  starOn: '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= book.star %>,
                });
              </script>
              <%= book.star %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td><%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
                <%= @book.user.name %>
              <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.category, search_book_path(keyword: @book.category) %></td>
          <td id="favorite_buttons_<%= @book.id %>">
            <%= render "favorites/btn",book: @book %>
          </td>
          <td>コメント数: <%= @book.book_comments.count %></td>
          <td>閲覧数: <%= @book_detail.view_counts.count %></td>
          <td>
            <span id="star-rate-<%= @book.id %>"></span>
            <script>
              $('#star-rate-<%= @book.id %>').raty({
                size: 36,
                starOff: '<%= asset_path('star-off.png') %>',
                starOn: '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.star %>,
              });
            </script>
            <%= @book.star %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <div id="comments_area">
        <%= render "book_comments/index",book: @book %>
      </div>
      <%= render "book_comments/form",book: @book,book_comment: @book_comment %>
    </div>
  </div>
</div>